def build(bld):
    module = bld.create_ns3_module('traffic-control', ['core', 'network'])
    module.source = [
      'model/traffic-control-layer.cc',
      'model/packet-filter.cc',
      'model/queue-disc.cc',
      'model/pfifo-fast-queue-disc.cc',
      'model/red-queue-disc.cc',
      'model/codel-queue-disc.cc',
      'model/fq-codel-queue-disc.cc',
      'model/pie-queue-disc.cc',
      'model/VirtualQueue.cc',
      'model/QueueCreate.cc',
      'helper/traffic-control-helper.cc',
      'helper/queue-disc-container.cc'
        ]

    module_test = bld.create_ns3_module_test_library('traffic-control')
    module_test.source = [
      'test/red-queue-disc-test-suite.cc',
      'test/codel-queue-disc-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'traffic-control'
    headers.source = [
      'model/traffic-control-layer.h',
      'model/packet-filter.h',
      'model/queue-disc.h',
      'model/pfifo-fast-queue-disc.h',
      'model/red-queue-disc.h',
      'model/codel-queue-disc.h',
      'model/fq-codel-queue-disc.h',
      'model/pie-queue-disc.h',
      'model/VirtualQueue.h',
      'model/QueueCreate.h',
      'helper/traffic-control-helper.h',
      'helper/queue-disc-container.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()